#!/usr/bin/env bash

# Check if an argument is provided for the file to be pushed
if [ -n "$1" ]; then
  file_to_push="$1"
  git add "$file_to_push"
else
  echo 'No file specified. Changes will be committed without adding a specific file.'
fi

echo 'Enter the commit message:'
read commitMessage

git commit -m "$commitMessage"

git push
