#!/usr/bin/env bash

# Check if an argument is provided for the file to be pushed
if [ -z "$1" ]; then
  echo 'No file specified. Please provide a file to push.'
  exit 1
fi

file_to_push="$1"

git add "$file_to_push"

echo 'Enter the commit message:'
read commitMessage

git commit -m "$commitMessage"

git push
